export const demoWorkItem = {
  identifier: "TESA-1",
  type: "Task",
  title: "Short title",
  body: "Ship the in-app work-item view. The work is the item, not a chat.",
  sections: [
    { title: "Acceptance Criteria", body: "Type stamp, facts rail, activity log." },
    { title: "In Scope", body: "This work-item screen." },
    { title: "Out of Scope", body: "Landing and nav." },
    { title: "Testing Strategies", body: "Targeted UI tests on TESA-1." },
  ],
  checklist: [{ id: "measure", label: "Measure a real task screen", done: false }],
  status: "New",
  assignee: "Unassigned",
  created: "just now",
  closed: "—",
  tokenUsage: "—",
  tokenCost: "—",
  bolt: "Coming",
  emptyActivity: "No activity yet.",
  composerPlaceholder: "Comment, or @ an agent",
} as const;
