#!/bin/bash
# INF-174: PR auto-creation — runs at 7am and 7pm EDT via n8n cron
# Queries issues WHERE test_status=passed AND pr_url IS NULL AND status=approved
# Groups by feature_branch, pushes and creates PR, notifies Discord + Telegram
set -euo pipefail

SUPA_URL="${NEXT_PUBLIC_SUPABASE_URL:?NEXT_PUBLIC_SUPABASE_URL is not set - see .env.local.template}"
SUPA_KEY="${SUPABASE_SERVICE_ROLE_KEY:?SUPABASE_SERVICE_ROLE_KEY is not set - see .env.local.template}"
MC_API="${MC_API_URL:-http://localhost:3000/api}"
DISCORD_CHANNEL="${DISCORD_PR_CHANNEL:-1487826368170299592}"

echo "[pr-window] Starting PR creation window..."

# Fetch passed issues without PR
ISSUES=$(curl -sf "$SUPA_URL/rest/v1/issues?test_status=eq.passed&pr_url=is.null&status=eq.approved&feature_branch=not.is.null&select=id,title,task_key,project,feature_branch,description" \
  -H "apikey: $SUPA_KEY" -H "Authorization: Bearer $SUPA_KEY")

COUNT=$(echo "$ISSUES" | jq 'length')
if [ "$COUNT" -eq 0 ]; then
  echo "[pr-window] No issues ready for PR"
  exit 0
fi

echo "[pr-window] $COUNT issues ready for PR creation"

# Group by feature_branch
BRANCHES=$(echo "$ISSUES" | jq -r '[.[].feature_branch] | unique | .[]')
PR_LIST=""

for BRANCH in $BRANCHES; do
  echo "[pr-window] Processing branch: $BRANCH"

  # Get all issues on this branch
  BRANCH_ISSUES=$(echo "$ISSUES" | jq -c "[.[] | select(.feature_branch == \"$BRANCH\")]")
  ISSUE_COUNT=$(echo "$BRANCH_ISSUES" | jq 'length')
  FIRST_PROJECT=$(echo "$BRANCH_ISSUES" | jq -r '.[0].project')

  # Determine repo
  if [ "$FIRST_PROJECT" = "Vespera" ]; then
    REPO_DIR="/var/folders/r0/hww7pxv12txb9sfmlmmw76xw0000gn/T/tmp.8qWeSvST6Z"
    REPO_SLUG="nabitllc/vespera"
  else
    REPO_DIR="${TODERO_DIR:-$HOME/mission-control}"
    REPO_SLUG="nabitllc/mission-control"
  fi

  cd "$REPO_DIR"

  # Push branch
  echo "[pr-window] Pushing $BRANCH..."
  git push origin "$BRANCH" 2>/dev/null || { echo "[pr-window] Push failed for $BRANCH"; continue; }

  # Build PR title and body using standard template
  TASK_KEYS=$(echo "$BRANCH_ISSUES" | jq -r '.[].task_key' | tr '\n' ', ' | sed 's/,$//')
  PR_TITLE="feat($TASK_KEYS): $(echo "$BRANCH_ISSUES" | jq -r '.[0].title' | head -c 50)"

  # Build AC checklist and issue links
  AC_CHECKLIST=""
  ISSUE_LINKS=""
  TEST_TIER="P2"
  while read -r ISSUE; do
    KEY=$(echo "$ISSUE" | jq -r '.task_key')
    TITLE=$(echo "$ISSUE" | jq -r '.title')
    DESC=$(echo "$ISSUE" | jq -r '.description // ""')
    ISSUE_LINKS="$ISSUE_LINKS- **$KEY**: $TITLE\n"
    # Extract AC lines from description if available
    if [ -n "$DESC" ] && [ "$DESC" != "null" ]; then
      AC_CHECKLIST="$AC_CHECKLIST- [x] $KEY: $(echo "$DESC" | head -1 | head -c 120)\n"
    else
      AC_CHECKLIST="$AC_CHECKLIST- [x] $KEY: $TITLE\n"
    fi
  done < <(echo "$BRANCH_ISSUES" | jq -c '.[]')

  PR_BODY="## Feature: $TASK_KEYS\n\n"
  PR_BODY="$PR_BODY**Issue:** $ISSUE_LINKS\n"
  PR_BODY="$PR_BODY## Acceptance Criteria\n\n$AC_CHECKLIST\n"
  PR_BODY="$PR_BODY## Test Tier\n\n**Test tier:** $TEST_TIER\n\n"
  PR_BODY="$PR_BODY## Tester Approval\n\n**Status:** passed\n\n"
  PR_BODY="$PR_BODY## Changes\n\nSee linked issues above for full details.\n\n"
  PR_BODY="$PR_BODY## Notes\n\n🤖 Generated by KAOS pipeline"

  # Create PR via gh
  PR_URL=$(cd "$REPO_DIR" && gh pr create --base main --head "$BRANCH" \
    --title "$PR_TITLE" --body "$(echo -e "$PR_BODY")" 2>/dev/null || echo "")

  if [ -z "$PR_URL" ]; then
    # PR might already exist
    PR_URL=$(cd "$REPO_DIR" && gh pr view "$BRANCH" --json url -q '.url' 2>/dev/null || echo "")
  fi

  if [ -n "$PR_URL" ]; then
    echo "[pr-window] PR created: $PR_URL"
    PR_LIST="$PR_LIST\n- [$TASK_KEYS]($PR_URL)"

    # Update pr_url on all issues in this branch
    echo "$BRANCH_ISSUES" | jq -r '.[].id' | while read -r ISSUE_ID; do
      curl -sf -X PATCH "$MC_API/issues" \
        -H "Content-Type: application/json" \
        -d "{\"id\":\"$ISSUE_ID\",\"pr_url\":\"$PR_URL\"}" >/dev/null 2>&1 || true
    done
  else
    echo "[pr-window] Failed to create PR for $BRANCH"
  fi
done

# Notify Discord + Telegram
if [ -n "$PR_LIST" ]; then
  MSG="🔀 **PR Window — $(date +%H:%M) EDT**\n\nPRs ready for review:$PR_LIST\n\n<@409194957098713088> please review"
  /opt/homebrew/bin/openclaw message send --channel discord --target "channel:$DISCORD_CHANNEL" --message "$MSG" 2>/dev/null || true
  /opt/homebrew/bin/openclaw message send --channel telegram --message "PR Window: $(echo "$PR_LIST" | wc -l | tr -d ' ') PRs ready for review" 2>/dev/null || true
  echo "[pr-window] Notifications sent"
fi

echo "[pr-window] PR window complete"
