import fs from "node:fs";
import path from "node:path";
import { randomBytes } from "node:crypto";
import { config as loadDotenv, parse as parseEnvFileContents } from "dotenv";
import { updateEnvFileContents, writeEnvFileAtomicallyIfChanged } from "@todero/shared/env-file";
import {
  aliasToderoEnvOntoLegacy,
  isOperatorOwnedEnvKey,
  operatorEnvKey,
  readOperatorEnv,
} from "@todero/shared/operator-env";
import { resolveConfigPath } from "./store.js";

const JWT_SECRET_ENV_KEY = operatorEnvKey("AGENT_JWT_SECRET");
function resolveEnvFilePath(configPath?: string) {
  return path.resolve(path.dirname(resolveConfigPath(configPath)), ".env");
}
const loadedEnvFiles = new Set<string>();

function isNonEmpty(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

function parseEnvFile(contents: string) {
  try {
    return parseEnvFileContents(contents);
  } catch {
    return {};
  }
}

function emptyEnvFileContents() {
  return [
    "# Todero environment variables",
    "# Generated by Todero CLI commands",
    "",
  ].join("\n");
}

function toderoOwnedEntries(entries: Record<string, string>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(entries).filter(
      ([key, value]) => isOperatorOwnedEnvKey(key) && value.trim().length > 0,
    ),
  );
}

function readJwtFromRecord(values: NodeJS.ProcessEnv | Record<string, string>): string | null {
  const raw = readOperatorEnv("AGENT_JWT_SECRET", values as NodeJS.ProcessEnv);
  return isNonEmpty(raw) ? raw.trim() : null;
}

export function resolveToderoEnvFile(configPath?: string): string {
  return resolveEnvFilePath(configPath);
}

export function resolveAgentJwtEnvFile(configPath?: string): string {
  return resolveEnvFilePath(configPath);
}

export function loadToderoEnvFile(configPath?: string): void {
  loadAgentJwtEnvFile(resolveEnvFilePath(configPath));
}

export function loadAgentJwtEnvFile(filePath = resolveEnvFilePath()): void {
  if (loadedEnvFiles.has(filePath)) return;

  if (!fs.existsSync(filePath)) return;
  loadedEnvFiles.add(filePath);
  loadDotenv({ path: filePath, override: false, quiet: true });
  aliasToderoEnvOntoLegacy();
}

export function readAgentJwtSecretFromEnv(configPath?: string): string | null {
  loadAgentJwtEnvFile(resolveEnvFilePath(configPath));
  return readJwtFromRecord(process.env);
}

export function readAgentJwtSecretFromEnvFile(filePath = resolveEnvFilePath()): string | null {
  if (!fs.existsSync(filePath)) return null;

  const raw = fs.readFileSync(filePath, "utf-8");
  const values = parseEnvFile(raw);
  return readJwtFromRecord(values);
}

export function ensureAgentJwtSecret(configPath?: string): { secret: string; created: boolean } {
  const existingEnv = readAgentJwtSecretFromEnv(configPath);
  if (existingEnv) {
    return { secret: existingEnv, created: false };
  }

  const envFilePath = resolveEnvFilePath(configPath);
  const existingFile = readAgentJwtSecretFromEnvFile(envFilePath);
  const secret = existingFile ?? randomBytes(32).toString("hex");
  const created = !existingFile;

  if (!existingFile) {
    writeAgentJwtEnv(secret, envFilePath);
  }

  return { secret, created };
}

export function writeAgentJwtEnv(secret: string, filePath = resolveEnvFilePath()): void {
  mergeToderoEnvEntries({ [JWT_SECRET_ENV_KEY]: secret }, filePath);
}

export function readToderoEnvEntries(filePath = resolveEnvFilePath()): Record<string, string> {
  if (!fs.existsSync(filePath)) return {};
  return parseEnvFile(fs.readFileSync(filePath, "utf-8"));
}

export function writeToderoEnvEntries(entries: Record<string, string>, filePath = resolveEnvFilePath()): void {
  const previousContents = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : null;
  const nextContents = updateEnvFileContents(previousContents ?? emptyEnvFileContents(), toderoOwnedEntries(entries), {
    valueEncoding: "minimal",
  });
  writeEnvFileAtomicallyIfChanged(filePath, previousContents, nextContents);
}

export function mergeToderoEnvEntries(
  entries: Record<string, string>,
  filePath = resolveEnvFilePath(),
): Record<string, string> {
  const current = readToderoEnvEntries(filePath);
  const managedEntries = toderoOwnedEntries(entries);
  const next = {
    ...current,
    ...managedEntries,
  };
  writeToderoEnvEntries(managedEntries, filePath);
  return next;
}
