#!/usr/bin/env bash
# spawn-context.sh — Workspace-aware spawn protocol helper (TOD-490)
# Reads SOUL.md, AGENTS.md key sections, and self-improving/memory.md
# and formats them as a context preamble for named-agent spawns.
#
# Usage:
#   bash scripts/spawn-context.sh [workspace_dir]
#   bash scripts/spawn-context.sh              # defaults to current dir
#
# Output: Formatted markdown context block to stdout.
# Intended to be captured and prepended to agent task prompts.

set -euo pipefail

WORKSPACE="${1:-.}"

emit_section() {
  local file="$1"
  local label="$2"
  if [[ -f "$file" ]]; then
    echo "## ${label}"
    echo ""
    cat "$file"
    echo ""
    echo "---"
    echo ""
  fi
}

emit_partial() {
  local file="$1"
  local label="$2"
  local start_pattern="$3"
  local max_lines="${4:-50}"
  if [[ -f "$file" ]]; then
    echo "## ${label}"
    echo ""
    # Extract from pattern to end, capped at max_lines
    sed -n "/${start_pattern}/,\$p" "$file" | head -n "$max_lines"
    echo ""
    echo "---"
    echo ""
  fi
}

echo "# Workspace Context"
echo ""
echo "> Auto-generated by spawn-context.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "> Workspace: ${WORKSPACE}"
echo ""
echo "---"
echo ""

# 1. SOUL.md — full (typically short, agent-specific guidance)
emit_section "${WORKSPACE}/SOUL.md" "SOUL (Agent Guidelines)"

# 2. AGENTS.md — key sections only (Agent table + Communication + Sprint Workflow)
AGENTS_FILE="${WORKSPACE}/AGENTS.md"
if [[ -f "$AGENTS_FILE" ]]; then
  echo "## AGENTS (System Overview)"
  echo ""
  # Agent table (first ~15 lines)
  head -n 15 "$AGENTS_FILE"
  echo ""
  # Agent Communication section
  emit_partial "$AGENTS_FILE" "Agent Communication Protocol" "^## Agent Communication" 20
  # Sprint Workflow section
  emit_partial "$AGENTS_FILE" "Sprint Workflow" "^## Sprint Workflow" 15
fi

# 3. self-improving/memory.md — if it exists
MEMORY_CANDIDATES=(
  "${WORKSPACE}/self-improving/memory.md"
  "${WORKSPACE}/.claude/memory/MEMORY.md"
  "${WORKSPACE}/docs/memory.md"
)
for memfile in "${MEMORY_CANDIDATES[@]}"; do
  if [[ -f "$memfile" ]]; then
    emit_section "$memfile" "Agent Memory (self-improving)"
    break
  fi
done

# 4. self-improving/corrections.md — recent corrections (last 30 entries max)
CORRECTIONS_FILE="${WORKSPACE}/self-improving/corrections.md"
if [[ -f "$CORRECTIONS_FILE" ]]; then
  echo "## Recent Corrections (self-improving)"
  echo ""
  # Show header + last 30 correction entries to keep context manageable
  head -n 6 "$CORRECTIONS_FILE"
  echo ""
  grep -A 10 "^### " "$CORRECTIONS_FILE" | tail -n 90
  echo ""
  echo "---"
  echo ""
fi

echo "# End Workspace Context"
