#!/usr/bin/env bash
# spawn-context.sh — Workspace-aware spawn protocol helper (TOD-490)
# Reads SOUL.md, AGENTS.md key sections, and self-improving/memory.md
# and formats them as a context preamble for named-agent spawns.
#
# memory-loop-retrieval piece: section 4 used to `cat` (well, `grep -A10 |
# tail -n90`, which is the same failure mode by a different name)
# self-improving/corrections.md WHOLESALE — every correction ever written for
# this agent, in file order, capped only by a fixed line count with no idea
# whether those 90 lines are relevant to the task about to be spawned. That is
# the exact bug this piece exists to fix: uncapped, unranked injection burying
# whatever record actually matters under everything else. Section 4 below now
# calls `scripts/retrieve-context.mjs`, which ranks this agent's run records
# (FTS5 search — see lib/memory-retrieval.ts) by relevance to AGENT_ID/TASK_KEY
# and injects only the top matches under a small, configurable, hard token
# budget. `set -euo pipefail` (below) means that if the budget is exceeded —
# the single most relevant record does not fit even alone — this script exits
# non-zero rather than silently injecting a truncated one. That is
# intentional: a caller of this script must see the failure, not a quietly
# shortened context.
#
# Usage:
#   bash scripts/spawn-context.sh [workspace_dir] [agent_id] [task_key] [task_title...]
#   bash scripts/spawn-context.sh                                # workspace_dir defaults to .
#   bash scripts/spawn-context.sh . builder TOD-1234 "Fix the thing"
#
# When agent_id/task_key are omitted, section 4 is skipped rather than run
# without knowing what to retrieve FOR — there is no task to rank relevance
# against, so "nothing" is the honest answer, not "everything" (the old
# behaviour) and not a guess.
#
# Output: Formatted markdown context block to stdout.
# Intended to be captured and prepended to agent task prompts.

set -euo pipefail

WORKSPACE="${1:-.}"
AGENT_ID="${2:-}"
TASK_KEY="${3:-}"
shift $(( $# < 3 ? $# : 3 )) || true
TASK_TITLE="$*"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

emit_section() {
  local file="$1"
  local label="$2"
  if [[ -f "$file" ]]; then
    echo "## ${label}"
    echo ""
    cat "$file"
    echo ""
    echo "---"
    echo ""
  fi
}

emit_partial() {
  local file="$1"
  local label="$2"
  local start_pattern="$3"
  local max_lines="${4:-50}"
  if [[ -f "$file" ]]; then
    echo "## ${label}"
    echo ""
    # Extract from pattern to end, capped at max_lines
    sed -n "/${start_pattern}/,\$p" "$file" | head -n "$max_lines"
    echo ""
    echo "---"
    echo ""
  fi
}

echo "# Workspace Context"
echo ""
echo "> Auto-generated by spawn-context.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "> Workspace: ${WORKSPACE}"
echo ""
echo "---"
echo ""

# 1. SOUL.md — full (typically short, agent-specific guidance)
emit_section "${WORKSPACE}/SOUL.md" "SOUL (Agent Guidelines)"

# 2. AGENTS.md — key sections only (Agent table + Communication + Sprint Workflow)
AGENTS_FILE="${WORKSPACE}/AGENTS.md"
if [[ -f "$AGENTS_FILE" ]]; then
  echo "## AGENTS (System Overview)"
  echo ""
  # Agent table (first ~15 lines)
  head -n 15 "$AGENTS_FILE"
  echo ""
  # Agent Communication section
  emit_partial "$AGENTS_FILE" "Agent Communication Protocol" "^## Agent Communication" 20
  # Sprint Workflow section
  emit_partial "$AGENTS_FILE" "Sprint Workflow" "^## Sprint Workflow" 15
fi

# 3. self-improving/memory.md — if it exists
MEMORY_CANDIDATES=(
  "${WORKSPACE}/self-improving/memory.md"
  "${WORKSPACE}/.claude/memory/MEMORY.md"
  "${WORKSPACE}/docs/memory.md"
)
for memfile in "${MEMORY_CANDIDATES[@]}"; do
  if [[ -f "$memfile" ]]; then
    emit_section "$memfile" "Agent Memory (self-improving)"
    break
  fi
done

# 4. Ranked, budgeted retrieval from the run-record store (memory-loop-retrieval).
# Replaces the old wholesale `corrections.md` dump. Needs an agent + a task to
# rank relevance against; without both, retrieval has nothing to search FOR,
# so this is skipped rather than guessed.
if [[ -n "$AGENT_ID" && -n "$TASK_KEY" ]]; then
  echo "## Relevant Past Experience (retrieved)"
  echo ""
  RETRIEVE_ERR_FILE="$(mktemp)"
  RETRIEVE_EXIT=0
  RETRIEVED="$(node "${REPO_ROOT}/scripts/retrieve-context.mjs" "$AGENT_ID" "$TASK_KEY" "$TASK_TITLE" 2>"$RETRIEVE_ERR_FILE")" || RETRIEVE_EXIT=$?
  if [[ "$RETRIEVE_EXIT" -eq 0 ]]; then
    if [[ -n "$RETRIEVED" ]]; then
      echo "$RETRIEVED"
    else
      echo "_(no past run record ranked relevant to this task)_"
    fi
  elif [[ "$RETRIEVE_EXIT" -eq 2 ]]; then
    # RetrievalBudgetExceededError — the single top-ranked matching record
    # cannot fit inside the configured budget on its own. This one STAYS
    # FATAL: silently continuing here is exactly the "truncate and lose the
    # record that mattered" failure this piece exists to prevent, so the
    # caller must see it, not a degraded-but-complete document.
    echo "retrieve-context.mjs exceeded its context budget (exit 2) — diagnostic follows:" >&2
    cat "$RETRIEVE_ERR_FILE" >&2
    rm -f "$RETRIEVE_ERR_FILE"
    exit 2
  else
    # Any other non-zero exit means the retrieval subprocess itself could not
    # complete cleanly — a usage error, a crash, an unhandled failure. This is
    # NOT the same thing as "searched and found nothing relevant" (that's the
    # RETRIEVE_EXIT -eq 0, empty-$RETRIEVED branch above). Print the real
    # diagnostic instead of discarding it (the old `2>/dev/null` here is
    # exactly what hid the previous failure from whoever had to debug it),
    # but DEGRADE rather than abort the whole spawn: a context document
    # that's merely missing retrieved memory is still usable by the agent
    # that spawns with it, whereas a document truncated before
    # "# End Workspace Context" is not.
    echo "retrieve-context.mjs exited ${RETRIEVE_EXIT} — diagnostic follows:" >&2
    cat "$RETRIEVE_ERR_FILE" >&2
    echo "_(retrieval unavailable — the run-record store could not be searched; this is NOT \"no relevant records\")_"
  fi
  rm -f "$RETRIEVE_ERR_FILE"
  echo ""
  echo "---"
  echo ""
fi

echo "# End Workspace Context"
